### ISSUE TITLE
How to track multiple markers?

### ISSUE THREAD

**Issue by SlavenLeskovar** [JMU-ROBOTICS-VIVA/ros2_aruco#11]
Hi, I have been trying to track 2 different markers at the same time with my drone camera. Im using this yaml file for launching but when the node starts, it only uses the last values, in this example values for DICT_6X6_1000 and neglects the first one. Is there a proper way to use these 2 types of markers at the same time?

```
/aruco_node:
  ros__parameters:
    marker_size: 0.132
    aruco_dictionary_id: DICT_7X7_1000
    image_topic: /image_raw
    camera_info_topic: /camera_info
/aruco_node:
  ros__parameters:
    marker_size: 0.132  
    aruco_dictionary_id: DICT_6X6_1000  
    image_topic: /image_raw  
    camera_info_topic: /camera_info  
```
