### ISSUE TITLE
Aruco Markers Position and Orientation is Empty

### ISSUE THREAD

**Issue by nabeeljadoon** [JMU-ROBOTICS-VIVA/ros2_aruco#7]
Hello I am using ros2 humble on ubuntu LTS 22.04 and I have successfully build this repo. However, when I run the aruco_recognition and node it detects the aruco marker but only info in "nanosec" parameter changes. 

The "position" and "orientation" info gets zero zero. please tell me what could be the problem.?

![Screenshot from 2023-06-18 03-46-53](https://github.com/JMU-ROBOTICS-VIVA/ros2_aruco/assets/19307307/f92bfaac-7c20-40dc-98c9-5871b825c83a)

**Comment by spragunr** [comment]
I'm guessing that your `/camera_info` topic doesn't contain calibration data for the camera.  If you echo `/camera_info` you should see something like the following:
```
header:
  stamp:
    sec: 1688652213
    nanosec: 40300000
  frame_id: camera
height: 480
width: 640
distortion_model: plumb_bob
d:
- -0.361976
- 0.11051
- 0.001014
- 0.000505
- 0.0
k:
- 438.783367
- 0.0
- 305.593336
- 0.0
- 437.302876
- 243.738352
- 0.0
- 0.0
- 1.0
r:
- 0.999978
- 0.002789
- -0.006046
- -0.002816
- 0.999986
- -0.004401
- 0.006034
- 0.004417
- 0.999972
p:
- 393.6538
- 0.0
- 322.797939
- 0.0
- 0.0
- 393.6538
- 241.090902
- 0.0
- 0.0
- 0.0
- 1.0
- 0.0
binning_x: 0
binning_y: 0
roi:
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: false
---
```
If all of the calibration fields are empty or contain 0, then the aruco localization will fail in the way you are seeing.
